version: "3.8"

services:
  demo-app:
    build:
      dockerfile: Dockerfile
      context: .
    image: demo-app
    container_name: demo-app
    ports:
      - "8000:8000"
    networks:
      - local-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: --config.file=/etc/prometheus/prometheus.yml
    hostname: prometheus
    networks:
      - local-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    hostname: grafana
    networks:
      - local-network

networks:
  local-network:
    name: local-network