#
# Build stage
#
FROM maven:3.6.0-jdk-11 AS build

WORKDIR /workspace
COPY pom.xml pom.xml
COPY java-console-with-prometheus java-console-with-prometheus
RUN mvn package

#
# Package stage
#
FROM openjdk:11
WORKDIR /workspace
COPY --from=build /workspace/java-console-with-prometheus/target/demo.jar demo.jar
COPY --from=build /workspace/java-console-with-prometheus/target/lib lib
# EXPOSE 8080

ENTRYPOINT ["java","-jar","demo.jar"]
