#
# Build stage
#
FROM maven:3.6.0-jdk-11 AS build

WORKDIR /workspace
COPY pom.xml pom.xml
RUN ls

# RUN mvn package -Pstage

#
# Package stage
#
# FROM openjdk:11
# COPY --from=build /workspace/web-app/target/cms-simulator.jar /app/cms-simulator.jar
# EXPOSE 8080
# ENTRYPOINT ["java","-jar","/app/cms-simulator.jar"]

# docker build -t cms-simulator:1.0.0 ..
# docker run -d -p 8090:8090 --name cms-simulator cms-simulator:1.0.0
