#
# Build stage
#
FROM maven:3.6.0-jdk-11 AS build

WORKDIR /workspace
COPY pom.xml pom.xml
COPY java-prometheus java-prometheus
RUN mvn package

#
# Package stage
#
FROM openjdk:11
WORKDIR /workspace
COPY --from=build /workspace/java-prometheus/target/demo.jar demo.jar
COPY --from=build /workspace/java-prometheus/target/lib lib 
# EXPOSE 8080
# ENTRYPOINT ["java","-jar","/app/cms-simulator.jar"]

# docker build -t cms-simulator:1.0.0 ..
# docker run -d -p 8090:8090 --name cms-simulator cms-simulator:1.0.0
